.data
.pushsection .hyp.reloc, "a"
.global __hyp_section_.hyp.idmap.text
.word 0
.reloc 0, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xaa8
.word 0
.reloc 4, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xab0
.global __hyp_section_.hyp.text
.global __hyp_section_.hyp.rodata
.word 0
.reloc 8, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c8
.word 0
.reloc 12, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e8
.word 0
.reloc 16, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f8
.word 0
.reloc 20, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x270
.word 0
.reloc 24, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x278
.word 0
.reloc 28, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b0
.word 0
.reloc 32, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d0
.word 0
.reloc 36, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x540
.word 0
.reloc 40, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x548
.word 0
.reloc 44, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x550
.word 0
.reloc 48, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x558
.word 0
.reloc 52, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x560
.word 0
.reloc 56, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x568
.word 0
.reloc 60, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x570
.word 0
.reloc 64, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x578
.word 0
.reloc 68, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x580
.word 0
.reloc 72, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x588
.word 0
.reloc 76, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x590
.word 0
.reloc 80, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x598
.word 0
.reloc 84, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5a0
.word 0
.reloc 88, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5a8
.word 0
.reloc 92, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5b0
.word 0
.reloc 96, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5b8
.word 0
.reloc 100, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5c0
.word 0
.reloc 104, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5c8
.word 0
.reloc 108, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5d0
.word 0
.reloc 112, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5d8
.word 0
.reloc 116, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5e0
.word 0
.reloc 120, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5e8
.word 0
.reloc 124, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x17c0
.word 0
.reloc 128, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x17d8
.word 0
.reloc 132, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1810
.word 0
.reloc 136, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1828
.word 0
.reloc 140, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1860
.word 0
.reloc 144, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1878
.word 0
.reloc 148, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x18b0
.word 0
.reloc 152, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x18c8
.word 0
.reloc 156, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1900
.word 0
.reloc 160, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1918
.word 0
.reloc 164, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1950
.word 0
.reloc 168, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1968
.word 0
.reloc 172, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x19a0
.word 0
.reloc 176, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x19b8
.word 0
.reloc 180, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x19f0
.word 0
.reloc 184, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a08
.word 0
.reloc 188, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a40
.word 0
.reloc 192, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a58
.word 0
.reloc 196, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a90
.word 0
.reloc 200, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1aa8
.word 0
.reloc 204, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ae0
.word 0
.reloc 208, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1af8
.word 0
.reloc 212, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b30
.word 0
.reloc 216, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b48
.word 0
.reloc 220, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b80
.word 0
.reloc 224, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b98
.word 0
.reloc 228, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1bd0
.word 0
.reloc 232, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1be8
.word 0
.reloc 236, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c20
.word 0
.reloc 240, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c38
.word 0
.reloc 244, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c70
.word 0
.reloc 248, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c88
.word 0
.reloc 252, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1cc0
.word 0
.reloc 256, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1cd8
.word 0
.reloc 260, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d10
.word 0
.reloc 264, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d28
.word 0
.reloc 268, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d60
.word 0
.reloc 272, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d78
.word 0
.reloc 276, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1dc8
.word 0
.reloc 280, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e00
.word 0
.reloc 284, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e18
.word 0
.reloc 288, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e50
.word 0
.reloc 292, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e68
.word 0
.reloc 296, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ea0
.word 0
.reloc 300, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1eb8
.word 0
.reloc 304, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f08
.word 0
.reloc 308, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f40
.word 0
.reloc 312, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f58
.word 0
.reloc 316, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f90
.word 0
.reloc 320, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1fa8
.word 0
.reloc 324, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ff8
.word 0
.reloc 328, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2048
.word 0
.reloc 332, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2080
.word 0
.reloc 336, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2098
.word 0
.reloc 340, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20e8
.word 0
.reloc 344, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2138
.word 0
.reloc 348, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2188
.word 0
.reloc 352, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21c0
.word 0
.reloc 356, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21d8
.word 0
.reloc 360, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2210
.word 0
.reloc 364, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2228
.word 0
.reloc 368, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2278
.word 0
.reloc 372, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22c8
.word 0
.reloc 376, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2300
.word 0
.reloc 380, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2318
.word 0
.reloc 384, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2350
.word 0
.reloc 388, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2368
.word 0
.reloc 392, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23b8
.word 0
.reloc 396, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2408
.word 0
.reloc 400, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2440
.word 0
.reloc 404, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2458
.word 0
.reloc 408, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2490
.word 0
.reloc 412, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24a8
.word 0
.reloc 416, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24e0
.word 0
.reloc 420, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24f8
.word 0
.reloc 424, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2548
.word 0
.reloc 428, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2598
.word 0
.reloc 432, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x25e8
.word 0
.reloc 436, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2638
.word 0
.reloc 440, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2688
.word 0
.reloc 444, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x26c0
.word 0
.reloc 448, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x26d8
.word 0
.reloc 452, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2710
.word 0
.reloc 456, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2728
.word 0
.reloc 460, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2760
.word 0
.reloc 464, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2778
.word 0
.reloc 468, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27c8
.word 0
.reloc 472, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2818
.word 0
.reloc 476, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2868
.word 0
.reloc 480, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28b8
.word 0
.reloc 484, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2908
.word 0
.reloc 488, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2940
.word 0
.reloc 492, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2958
.word 0
.reloc 496, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2990
.word 0
.reloc 500, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29a8
.word 0
.reloc 504, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29e0
.word 0
.reloc 508, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29f8
.word 0
.reloc 512, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a30
.word 0
.reloc 516, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a48
.word 0
.reloc 520, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a80
.word 0
.reloc 524, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a98
.word 0
.reloc 528, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ad0
.word 0
.reloc 532, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ae8
.word 0
.reloc 536, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b20
.word 0
.reloc 540, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b38
.word 0
.reloc 544, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b70
.word 0
.reloc 548, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b88
.word 0
.reloc 552, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2bc0
.word 0
.reloc 556, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c10
.word 0
.reloc 560, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c60
.word 0
.reloc 564, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cb0
.word 0
.reloc 568, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cc8
.word 0
.reloc 572, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d00
.word 0
.reloc 576, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d50
.word 0
.reloc 580, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2da0
.word 0
.reloc 584, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2df0
.word 0
.reloc 588, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e40
.word 0
.reloc 592, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e90
.word 0
.reloc 596, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ee0
.popsection
