# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-model-a.dtb
dtb-$(CONFIG_ARCH_MXC) += imx91-debix-bmb-13-a1.dtb
dtb-$(CONFIG_ARCH_MXC) += imx91-debix-bmb-13-a2.dtb
dtb-$(CONFIG_ARCH_MXC) += imx93-debix-bmb-13-a1.dtb
dtb-$(CONFIG_ARCH_MXC) += imx93-debix-bmb-13-a2.dtb

subdir-y += debix-model-a


DTC_FLAGS := -@
DTC_FLAGS_imx8mp-debix-model-a.dtb += -@
